Fix compile warning
The content of warning:

Compiling 1 file (.ex)
warning: incompatible types:

    map() !~ atom()

in expression:

    # lib/params.ex:128
    module.__changeset__

where "module" was given the type atom() in:

    # lib/params.ex:126
    is_atom(module)

where "module" was given the type map() (due to calling var.field) in:

    # lib/params.ex:128
    module.__changeset__

HINT: "var.field" (without parentheses) implies "var" is a map() while "var.fun()" (with parentheses) implies "var" is an atom()

Conflict found at
  lib/params.ex:128: Params.optional/1